import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./app.css";
import DatePickerLocalization from "./datepicker_localization";
import { Box, CssBaseline, ThemeProvider, Toolbar } from "@mui/material";
import theme from "./theme";
import CustomDrawer from "./ui/app-layout/drawer";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto'
});

export const metadata: Metadata = {
  title: "HyperStrength Fitness Tracker",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={roboto.variable}>
      <body>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <Box sx={{ display: 'flex' }}>
            <CustomDrawer />
            <Box component="main" sx={{
              flexGrow: 1
            }}>
              <Toolbar variant="dense" />
              <DatePickerLocalization>
                {children}
              </DatePickerLocalization>
            </Box>
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
