import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";
import DatePickerLocalization from "./datepicker_localization";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fit Journey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <DatePickerLocalization>
          {children}
        </DatePickerLocalization>
      </body>
    </html>
  );
}
