import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import './globals.css'
import Wrappers from "./ui/app-layout/wrappers";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto'
});


export const metadata: Metadata = {
  title: "HyperStrength Fitness Tracker",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={roboto.variable}>
      <body>
        <Wrappers>
          {children}
        </Wrappers>
      </body>
    </html >
  );
}